# Generated by Django 5.1.6 on 2025-03-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название лекарства')),
                ('medicament_type', models.CharField(choices=[('tablet', 'Таблетка'), ('capsule', 'Капсула'), ('spray', 'Спрей'), ('ointment', 'Мазь'), ('cream', 'Крем'), ('bandage', 'Бинт'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип лекарства')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
            },
        ),
        migrations.CreateModel(
            name='MedicineBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название коробки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Коробка с лекарствами',
                'verbose_name_plural': 'Коробки с лекарствами',
            },
        ),
        migrations.CreateModel(
            name='Ointment',
            fields=[
                ('medicament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='healthbox.medicament')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес (г)')),
                ('texture', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текстура')),
            ],
            options={
                'verbose_name': 'Мазь',
                'verbose_name_plural': 'Мази',
            },
            bases=('healthbox.medicament',),
        ),
        migrations.CreateModel(
            name='Spray',
            fields=[
                ('medicament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='healthbox.medicament')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объем (мл)')),
                ('nozzle_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип распылителя')),
            ],
            options={
                'verbose_name': 'Спрей',
                'verbose_name_plural': 'Спреи',
            },
            bases=('healthbox.medicament',),
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('medicament_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='healthbox.medicament')),
                ('dosage', models.CharField(max_length=50, verbose_name='Дозировка')),
                ('shape', models.CharField(blank=True, max_length=50, null=True, verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Таблетка',
                'verbose_name_plural': 'Таблетки',
            },
            bases=('healthbox.medicament',),
        ),
        migrations.AddField(
            model_name='medicament',
            name='medicine_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='healthbox.medicinebox', verbose_name='Коробка'),
        ),
    ]
