# Generated by Django 5.2.15 on 2026-06-09 18:20

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("trade_name", models.CharField(max_length=180)),
                ("active_ingredient", models.CharField(blank=True, max_length=180)),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("tablets", "Tablets"),
                            ("syrup", "Syrup"),
                            ("ointment", "Ointment"),
                            ("drops", "Drops"),
                            ("capsules", "Capsules"),
                            ("spray", "Spray"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("dosage", models.CharField(blank=True, max_length=120)),
                ("quantity", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("ml", "ml"),
                            ("g", "g"),
                            ("piece", "Piece"),
                            ("drop", "Drop"),
                            ("other", "Other"),
                        ],
                        default="piece",
                        max_length=20,
                    ),
                ),
                ("expiry_date", models.DateField()),
                (
                    "storage",
                    models.CharField(
                        choices=[("kit", "Kit"), ("fridge", "Fridge"), ("kids_kit", "Kids kit")],
                        default="kit",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="medicine_photos/")),
                (
                    "instruction_file",
                    models.FileField(blank=True, null=True, upload_to="medicine_instructions/"),
                ),
                ("instruction_url", models.URLField(blank=True)),
                ("instruction_note", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("reference_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_medicines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="accounts.family",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date", "trade_name"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("note", models.TextField(blank=True)),
                ("is_bought", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shopping_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_items",
                        to="accounts.family",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_items",
                        to="medicines.medicine",
                    ),
                ),
            ],
            options={
                "ordering": ["is_bought", "-created_at", "-id"],
            },
        ),
    ]
