# Generated by Django 5.2.15 on 2026-06-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="low_stock_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Остаток, при котором лекарство считается заканчивающимся; пусто — не отслеживать.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
