# Generated by Django 5.2.15 on 2026-06-12 09:16

import django.core.validators
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0002_medicine_low_stock_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="instruction_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="medicine_instructions/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "webp"]
                    ),
                    core.validators.validate_instruction_file_size,
                    core.validators.validate_instruction_file_content,
                ],
            ),
        ),
    ]
