# Generated by Django 5.2.15 on 2026-06-12 09:40

import django.core.validators
from django.db import migrations, models

import core.uploads
import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0003_alter_medicine_instruction_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="instruction_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.uploads.medicine_instruction_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "webp"]
                    ),
                    core.validators.validate_instruction_file_size,
                    core.validators.validate_instruction_file_content,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads.medicine_photo_upload_to),
        ),
    ]
