# Generated by Django 5.2.15 on 2026-06-13 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0004_alter_medicine_instruction_file_alter_medicine_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="photo",
        ),
    ]
